# version: '3.9'

# services:
#   backend:
#     build:
#       context: ./backend
#     ports:
#       - "8000:8000"
#     volumes:
#       - ./backend/app:/app
#     container_name: chatbot-backend
version: '3.9'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
    container_name: chatbot-backend

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    container_name: chatbot-frontend
